runtime: python311
env: standard
service: chat-bot-1

# get environment variables from secrets
env_variables:
  OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}

runtime_config:
  document_root: public

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10